import { ArrowLeft, ArrowRight, CheckCircle2, Database, MapPin } from 'lucide-react';
import { Link } from 'react-router-dom';
import heroMap from '../assets/hero_map.png';
import infrastructureMap from '../assets/01_Public_Transport_Infrastructure_Distribution.png';
import concentrationMap from '../assets/02_Transport_Infrastructure_Concentration.png';
import coverageMap from '../assets/03_LSOA_Coverages_Map.png';
import populationMap from '../assets/04_LSOA_Population_Coverage_Map copy.png';

const metadata = [['Location', 'Greater Manchester, UK'], ['Role', 'Geospatial Analyst'], ['Software', 'QGIS'], ['Analysis unit', 'LSOA'], ['CRS', 'British National Grid (EPSG:27700)']];
const datasets = [['13,385', 'Active bus stops'], ['99', 'Metrolink stops'], ['91', 'Railway stations'], ['100 m', 'WorldPop grid']];
const areaResults = [['90.6%', 'Bus', 'Average LSOA area coverage'], ['17.6%', 'Metrolink', 'Average LSOA area coverage'], ['27.6%', 'Rail', 'Average LSOA area coverage'], ['89.0%', 'Combined', 'Average LSOA area coverage']];
const populationResults = [['97.9%', 'Bus', 'Residents within 400 m'], ['18.8%', 'Metrolink', 'Residents within 800 m'], ['28.9%', 'Rail', 'Residents within 1 km'], ['98.6%', 'Overall', 'Residents near at least one mode']];
const findings = [['01', 'Extensive Bus Coverage', "Bus infrastructure has the widest reach and provides accessibility to approximately 97.9% of Greater Manchester's population."], ['02', 'Corridor-Based Rail Networks', 'Metrolink and railway accessibility is more concentrated and closely follows established network corridors.'], ['03', 'High Overall Coverage', 'Approximately 98.6% of residents live within the defined walking distance of at least one public transport mode.'], ['04', 'Spatial Inequality Remains', 'Accessibility is strongest around urban and transport centres and becomes more fragmented towards peripheral areas.']];
const limitations = [['Straight-Line Distance', 'Catchments use straight-line distance rather than pedestrian-network routes.'], ['Walking Environment', 'Physical barriers and actual walking conditions are not represented.'], ['Service Quality', 'Frequency, reliability, operating hours and journey time are outside the analysis.'], ['Provision Index', 'Bus, Metrolink and rail infrastructure are equally weighted.']];

function Label({ children }) { return <p className="text-xs font-bold uppercase tracking-[0.24em] text-[rgb(144_224_239)]">{children}</p>; }
function MapFigure({ src, alt, title, caption }) { return <figure className="overflow-hidden rounded-3xl border border-white/10 bg-slate-900 shadow-2xl"><img src={src} alt={alt} className="h-auto w-full" /><figcaption className="border-t border-white/10 p-5"><p className="font-display font-semibold text-white">{title}</p><p className="mt-2 text-sm leading-6 text-slate-400">{caption}</p></figcaption></figure>; }
function Process({ steps }) { return <div className="flex flex-wrap items-center gap-2">{steps.map((step, index) => <div className="contents" key={step}><span className="rounded-full border border-cyan-200/15 bg-cyan-200/[0.06] px-3 py-2 text-xs font-semibold text-cyan-50">{step}</span>{index < steps.length - 1 && <ArrowRight aria-hidden="true" className="h-4 w-4 text-cyan-200/35" />}</div>)}</div>; }
function StatGrid({ items }) { return <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{items.map(([value, label, detail]) => <div key={label} className="rounded-2xl border border-white/[0.07] bg-slate-900/70 p-5"><p className="font-display text-3xl font-semibold text-[rgb(144_224_239)]">{value}</p><p className="mt-2 font-bold text-white">{label}</p>{detail && <p className="mt-1 text-xs leading-5 text-slate-400">{detail}</p>}</div>)}</div>; }

function GreaterManchesterCaseStudy() {
  return (
    <main className="portfolio-case-study portfolio-gis-case-study min-h-screen pt-20">
      <article>
        <header className="mx-auto w-full max-w-7xl px-5 py-14 sm:px-8 lg:px-12 lg:py-20">
          <nav aria-label="Breadcrumb" className="text-sm text-slate-400"><Link to="/projects" className="hover:text-cyan-200">Projects</Link><span className="mx-2">/</span><span className="text-slate-200">Greater Manchester Transport Accessibility</span></nav>
          <div className="mt-10 grid items-center gap-10 lg:grid-cols-[0.7fr_1.3fr]">
            <div>
              <Label>GIS · Spatial Analysis · Transport Accessibility</Label><h1 className="font-display mt-5 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">Assessing Public Transport Accessibility Across Greater Manchester Using GIS</h1><p className="mt-6 text-lg leading-8 text-slate-300">A spatial analysis of how bus, Metrolink and rail infrastructure is distributed, how much of the region falls within reasonable walking distance, and how many residents are served.</p><div className="mt-7 flex flex-wrap gap-2">{['QGIS', 'Spatial Analysis', 'Raster Analysis', 'Zonal Statistics', 'Cartography'].map((tag) => <span key={tag} className="rounded-full border border-cyan-200/15 bg-cyan-200/[0.07] px-3 py-1.5 text-xs text-cyan-50">{tag}</span>)}</div>
            </div>
            <figure className="overflow-hidden rounded-3xl border border-cyan-200/15 bg-slate-900 shadow-2xl">
              <a href={heroMap} target="_blank" rel="noreferrer" aria-label="Open the Greater Manchester project map at full resolution">
                <img src={heroMap} alt="Greater Manchester transport accessibility project overview map" className="block h-auto w-full object-contain" />
              </a>
              <figcaption className="border-t border-white/10 px-5 py-3 text-right text-xs font-semibold text-[rgb(144_224_239)]">Select map to view full resolution</figcaption>
            </figure>
          </div>
          <div className="mt-10 grid gap-4 border-y border-white/10 py-7 sm:grid-cols-2 lg:grid-cols-5">{metadata.map(([label, value]) => <div key={label}><p className="text-[0.65rem] font-bold uppercase tracking-[0.18em] text-cyan-200/45">{label}</p><p className="mt-2 text-sm font-semibold text-slate-100">{value}</p></div>)}</div>
        </header>

        <div className="mx-auto w-full max-w-6xl space-y-28 px-5 pb-24 sm:px-8 lg:px-12">
          <section className="grid gap-10 lg:grid-cols-2"><div><Label>Project overview</Label><h2 className="font-display mt-4 text-3xl font-semibold sm:text-4xl">Understanding public transport accessibility</h2><p className="mt-5 leading-8 text-slate-300">Public transport infrastructure is not distributed evenly across Greater Manchester. This project examines where it is concentrated and whether its geographical distribution translates into meaningful accessibility for communities and residents.</p></div><div className="space-y-3">{[['01', 'Infrastructure', 'Where is public transport infrastructure concentrated?'], ['02', 'Spatial Coverage', 'How much of each LSOA falls within walking distance?'], ['03', 'Population Coverage', 'How many residents live within those areas?']].map(([number, title, text]) => <div key={number} className="flex gap-4 rounded-2xl border border-white/[0.07] bg-slate-900/60 p-5"><span className="font-display text-xl text-[rgb(144_224_239)]">{number}</span><div><h3 className="font-display font-semibold">{title}</h3><p className="mt-1 text-sm text-slate-400">{text}</p></div></div>)}</div></section>

          <section><div className="flex items-center gap-3"><MapPin className="h-5 w-5 text-cyan-200" /><Label>Study area & data</Label></div><h2 className="font-display mt-4 text-3xl font-semibold">Greater Manchester at LSOA level</h2><p className="mt-4 max-w-3xl leading-8 text-slate-300">The analysis uses consistent small-area geography alongside transport infrastructure, administrative boundaries and gridded population data from the Department for Transport, ONS, OpenStreetMap and WorldPop.</p><div className="mt-8"><StatGrid items={datasets} /></div></section>

          <section><Label>01 / Infrastructure</Label><h2 className="font-display mt-4 max-w-4xl text-3xl font-semibold sm:text-4xl">Where is public transport infrastructure concentrated?</h2><p className="mt-5 max-w-3xl leading-8 text-slate-300">Bus, Metrolink and rail counts were standardised to a common 0–1 scale and equally weighted to create a Transport Infrastructure Provision Index. Bus-stop density accounts for differences in LSOA area.</p><div className="mt-7"><Process steps={['Transport Stops', 'Spatial Join', 'LSOA Counts', 'Density', 'Normalisation', 'Provision Index']} /></div><div className="mt-10 space-y-8"><MapFigure src={infrastructureMap} alt="Maps showing bus, Metrolink and rail infrastructure distribution across Greater Manchester" title="Map 01 — Infrastructure Distribution" caption="Bus infrastructure has the widest spatial distribution, while Metrolink and rail are concentrated along established transport corridors." /><MapFigure src={concentrationMap} alt="Maps showing bus stop density and the combined transport infrastructure provision index" title="Map 02 — Density & Provision" caption="High provision is visible around Manchester city centre, Trafford Park, Wigan Central and Gorse Hill." /></div></section>

          <section><Label>02 / Spatial Accessibility</Label><h2 className="font-display mt-4 max-w-4xl text-3xl font-semibold sm:text-4xl">How much of each LSOA falls within walking distance?</h2><div className="mt-8 grid gap-3 sm:grid-cols-3">{[['Bus', '400 m'], ['Metrolink', '800 m'], ['Rail', '1 km']].map(([mode, distance]) => <div key={mode} className="rounded-2xl border border-cyan-200/15 bg-cyan-200/[0.05] p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-400">{mode}</p><p className="font-display mt-2 text-3xl text-[rgb(144_224_239)]">{distance}</p><p className="mt-1 text-xs text-slate-400">Walking-distance catchment</p></div>)}</div><div className="mt-7"><Process steps={['Transport Stops', 'Buffer', 'Dissolve', 'LSOA Intersection', 'Accessible Area', 'Coverage %']} /></div><div className="mt-10"><MapFigure src={coverageMap} alt="Four maps comparing bus, Metrolink, rail and combined LSOA area coverage" title="Spatial Accessibility Maps" caption="Overlapping catchments were dissolved before calculation, preventing the same geographical area from being counted more than once." /></div><div className="mt-8"><StatGrid items={areaResults} /></div><p className="mt-6 rounded-2xl border-l-2 border-cyan-200 bg-slate-900/60 p-5 leading-7 text-slate-300">Combined accessibility is strongest around the urban core and becomes increasingly fragmented towards peripheral areas.</p></section>

          <section><Label>03 / Population Accessibility</Label><h2 className="font-display mt-4 max-w-4xl text-3xl font-semibold sm:text-4xl">How many residents live within walking distance?</h2><p className="mt-5 max-w-3xl leading-8 text-slate-300">A 100 m WorldPop 2021 population raster estimates residents within each catchment. Dissolving combined zones prevents people inside overlapping catchments from being counted more than once.</p><div className="mt-7"><Process steps={['WorldPop 2021', 'Reproject', 'Clip', 'Catchments', 'Zonal Statistics', 'Population Coverage']} /></div><div className="mt-10"><MapFigure src={populationMap} alt="Four maps comparing population accessibility to bus, Metrolink, rail and all modes" title="Population Accessibility Maps" caption="The maps move beyond accessible land area to estimate how many residents are served by each transport mode." /></div><div className="mt-8"><StatGrid items={populationResults} /></div><div className="mt-8 rounded-3xl border border-cyan-200/20 bg-cyan-200/[0.06] p-7"><Label>Key insight</Label><p className="font-display mt-3 text-2xl font-semibold">Bus provides the backbone of population accessibility.</p><p className="mt-3 leading-7 text-slate-300">Bus services reach most residents captured by the combined measure. Metrolink and rail extend accessibility to a smaller additional share while providing important corridor connections.</p></div></section>

          <section><Label>What the analysis revealed</Label><div className="mt-7 grid gap-4 sm:grid-cols-2">{findings.map(([number, title, text]) => <div key={number} className="rounded-2xl border border-white/[0.07] bg-slate-900/60 p-6"><span className="font-display text-xl text-cyan-200/45">{number}</span><h3 className="font-display mt-3 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></div>)}</div></section>

          <section><div className="flex items-center gap-3"><Database className="h-5 w-5 text-cyan-200" /><Label>Technical workflow & skills</Label></div><div className="mt-7"><Process steps={['Data Acquisition', 'Cleaning', 'CRS Management', 'Spatial Joins', 'Buffer & Intersection', 'Raster Processing', 'Zonal Statistics', 'Cartography']} /></div><div className="mt-8 flex flex-wrap gap-2">{['QGIS', 'Vector Analysis', 'Raster Analysis', 'Spatial Joins', 'Buffer', 'Dissolve', 'Intersection', 'EPSG:27700', 'WorldPop', 'ONS Geography', 'OpenStreetMap', 'Min-Max Normalisation'].map((skill) => <span key={skill} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-2 text-xs text-slate-300"><CheckCircle2 className="h-3.5 w-3.5 text-cyan-200" />{skill}</span>)}</div></section>

          <section><Label>Limitations</Label><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{limitations.map(([title, text]) => <div key={title} className="rounded-2xl border border-white/[0.07] bg-slate-900/60 p-5"><h3 className="font-display font-semibold">{title}</h3><p className="mt-3 text-xs leading-5 text-slate-400">{text}</p></div>)}</div></section>

          <section className="rounded-3xl border border-cyan-200/15 bg-slate-900/70 p-7 sm:p-10"><Label>Data sources</Label><div className="mt-6 grid gap-6 sm:grid-cols-3"><div><h3 className="font-display font-semibold">Transport</h3><p className="mt-2 text-sm leading-6 text-slate-400">Department for Transport, National Bus Open Data Service, Greater Manchester Metrolink Network and OpenStreetMap.</p></div><div><h3 className="font-display font-semibold">Geography</h3><p className="mt-2 text-sm leading-6 text-slate-400">Office for National Statistics LSOA boundaries.</p></div><div><h3 className="font-display font-semibold">Population</h3><p className="mt-2 text-sm leading-6 text-slate-400">WorldPop 2021, 100 m gridded population.</p></div></div></section>

          <footer className="flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-8"><Link to="/projects" className="inline-flex items-center gap-2 font-bold text-[rgb(144_224_239)]"><ArrowLeft className="h-4 w-4" /> Back to projects</Link><Link to="/projects/practical-qgis-projects" className="inline-flex items-center gap-2 font-bold text-white">Next project <ArrowRight className="h-4 w-4" /></Link></footer>
        </div>
      </article>
    </main>
  );
}

export default GreaterManchesterCaseStudy;
